name: Test Template

on:
  workflow_call:
    inputs:
      testConfigFile:
        required: true
        type: string
      testResultsDir:
        required: false
        type: string
        default: 'syntestio-test-results'
      os:
        required: true
        type: string
        default: 'linux'
      runner:
        required: false
        type: string
        default: 'ubuntu-latest'
      cliArguments:
        required: false
        type: string
        default: '--headless'
      continueOnError:
        required: false
        type: boolean
        default: true

jobs:
  run-tests:
    runs-on: ${{ inputs.runner != '' && inputs.runner || format('{0}-latest', inputs.os) }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Create artifacts directory
        run: |
          mkdir -p ${{ github.workspace }}/${{ inputs.testResultsDir }}

      - name: Copy test files
        run: |
          # Only copy the config file if it's not already in the workspace root
          CONFIG_FILENAME=$(basename ${{ inputs.testConfigFile }})
          if [ "${{ inputs.testConfigFile }}" != "$CONFIG_FILENAME" ]; then
            cp ${{ inputs.testConfigFile }} ${{ github.workspace }}/
          fi

          # Copy feature files from the config directory
          cp $(dirname ${{ inputs.testConfigFile }})/**/*.feature ${{ github.workspace }}/ 2>/dev/null || true

      - name: Install CLI package
        run: |
          npm install -g @syntestio/cli-${{ inputs.os }} --verbose

      - name: Run test scenario
        continue-on-error: ${{ inputs.continueOnError }}
        run: |
          # Set UTF-8 encoding
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8

          echo "Starting test execution..."

          # Run tests and capture output
          syn --config "${{ github.workspace }}/${{ inputs.testConfigFile }}" ${{ inputs.cliArguments }} 2>&1 | tee syntestio_test_output.log
          TEST_EXIT_CODE=${PIPESTATUS[0]}

          echo "Test execution completed with exit code: $TEST_EXIT_CODE"

          # Copy test reports to artifacts
          if ls TestReport_*.html 1> /dev/null 2>&1; then
            echo "Copying test reports to artifacts directory..."
            cp TestReport_*.html ${{ github.workspace }}/${{ inputs.testResultsDir }}/
            cp syntestio_test_output.log ${{ github.workspace }}/${{ inputs.testResultsDir }}/
          else
            echo "No test reports found!"
            echo "::warning::No test reports were generated"
          fi

          # Set job status based on test results
          if [ $TEST_EXIT_CODE -ne 0 ]; then
            echo "::warning::Tests failed with exit code: $TEST_EXIT_CODE"
            exit 1
          else
            echo "All tests passed successfully"
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: syntestio-test-reports
          path: ${{ github.workspace }}/${{ inputs.testResultsDir }}/
